- name: Create a project on loop based on dictionary in defaults/main.yml
  k8s:
    api_version: v1
    kind: Namespace
    name: "{{ item.key }}"
    #description: "{{ item.value.project_creation_desc }}"
    #display_name: "{{ item.value.project_creation_display_name }}"
    state: present
  with_dict: "{{ projects }}"